name: grocery_scanner_demo
description: Demo app: scan barcode and lookup product (Open Food Facts)
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^2.0.0
  http: ^0.13.5
  sqflite: ^2.2.7
  path_provider: ^2.0.14
  path: ^1.8.3
